sudo: required
dist: xenial
branches:
  - master
services:
  - docker
go_import_path: github.com/pauldotknopf/darch
before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo apt-get install -y debootstrap
  - sudo service docker restart
script:
  - sudo make ci LOGIN_USERNAME=$DOCKER_LOGIN_USERNAME LOGIN_PASSWORD=$DOCKER_LOGIN_PASSWORD TAG=`date +"%Y-%m-%d-%H%M%S"`