sudo: required
dist: xenial
services:
  - docker
go_import_path: github.com/pauldotknopf/darch
before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
script:
  - make ci LOGIN_USERNAME=$DOCKER_LOGIN_USERNAME LOGIN_PASSWORD=$DOCKER_LOGIN_PASSWORD TAG=`date +"%Y-%m-%d-%H%M%S"`